spring:
  application:
    name: springboot_lvfang
  profiles:
    active: dev

server:
  port: 80
  servlet:
    context-path: /

logging:
    level:
        com: debug
    pattern:
      dateformat: yyyy-MM-dd HH:mm:ss

